### PR TITLE
Add a new encode error type "skip" for ulatex to skip unknown chars.

### PR DESCRIPTION
**Pull request by xuhdev**
Also, we need to add these to the documentation.

### CODE REVIEW

**Comment by xuhdev** [comment]
If you think it's better to handle `ignore` differently for "ulatex" instead of creating `skip`, I can make the change.  Also, if you merge this PR, can you make a new release? I consider this feature is required by the writing bib file feature in pybtex.

**Comment by mcmtroffaes** [comment]
Do I understand correctly from the code that you're suggesting a "skip" mode which keeps unicode characters inside the latex output if translation to bytes fails?

If so, can you explain to me why you would not simply use the ulatex+utf8 encoder instead (if the user wants a unicode-enabled bibtex file)? This will automatically keep all utf8 characters, whilst also converting any special characters (\, #, &, ...) as required.

**Comment by mcmtroffaes** [comment]
... hmm, looking at the code, the encoding option is broken for the ulatex codec. Something looks amiss, I'm checking it.

**Comment by mcmtroffaes** [comment]
I've added a test for it, and it seems to be working as expected. Please let me know if the ulatex+utf8 codec does the trick for you or not!

**Comment by xuhdev** [comment]
@mcmtroffaes Thanks for your response. It seems `ulatex+utf8` works by not converting utf-8 characters at all, but I would like to achieve the effect that known accented characters are converted (something like `ö`-->`\"o`), so I can try to keep compatibility as much as possible, while don't throw errors when unknown UTF-8 characters are encountered. Is it possible to do so?

**Comment by xuhdev** [comment]
What do you think?

**Comment by mcmtroffaes** [comment]
Superseded by #46

**Pull request closed without merging**
