### PR TITLE
Add support for "backslash" and "tilde"

### PR DESCRIPTION
**Pull request by xuhdev**

### CODE REVIEW

**Comment by xuhdev** [comment]
I can't manage to encode backslashes though...

**Comment by mcmtroffaes** [comment]
The failures are due to new style errors being picked up by flake8, no problem there.

The tilde is fine. The backslash, I'm not so sure we should do any translation. There may be cases in the wild where folks will write "\somecommand" in unicode but want to retain "\somecommand" in latex, rather than "\backslash somecommand"...

A unit test would be nice too.

**Comment by mcmtroffaes** [comment]
The flake8 issues are fixed in develop, so a rebase should be enough to take care of the travis failures.

**Comment by xuhdev** [comment]
OK, now rebased and some tests are added

**Comment by mcmtroffaes** [comment]
Thanks a lot for the work and the quick rebase! I've finished reviewing this - if you can do the changes, great - if not I can do it too in the next few days.

**Comment by mcmtroffaes** [comment]
Let's continue the discussion here. I don't get in any way how tilde rendering is relevant to nbsp or combining characters... The purpose of the codec is to have a simple & logical one-to-one correspondence between unicode characters and latex commands. There are simple tilde characters in both unicode and latex so we simply need to find a logical way of connecting these latex commands:

```
\textasciitilde
\~{}
\texttildelow
$\sim$
```

with these unicode symbols:

```
~
\N{SMALL TILDE}
\N{MODIFIED LETTER LOW TILDE}
\N{TILDE OPERATOR}
```

A bit more googling for "latex text centered tilde" lead me to http://tex.stackexchange.com/a/2883 so now I'm pretty convinced that it makes sense to connect ``\textasciitilde`` to a plain unicode ~.

So I suggest to connect them in the order as given above. This is simple and understandable, no surprises anywhere. The fact that ``\texttildelow`` gives a non-low tilde in some fonts is arguably a bug as well (just look at the name of the command...).

**Comment by xuhdev** [comment]
I've updated the PR and removed all combined characters for now. The conversion is according to the following:

```
\textasciitilde
\~{}
\texttildelow
$\sim$
```

corresponds to

```
~
\N{SMALL TILDE}
\N{MODIFIED LETTER LOW TILDE}
\N{TILDE OPERATOR}
```

accordingly.

**Comment by mcmtroffaes** [comment]
Looks great, thanks for all your work on this - and apologies for all the nagging... but it's been a useful discussion, I learnt a few things whilst at it.

**Comment by xuhdev** [comment]
No problem... we always learn from discussions.

**Pull request merged**
